//addSbtPlugin("io.swagger.core.v3" % "swagger-annotations" % "2.2.4")
//addSbtPlugin("io.swagger.core.v3" % "swagger-models" % "2.2.4")
//addSbtPlugin("io.swagger.core.v3" % "swagger-core" % "2.2.4")
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.15")
addSbtPlugin("com.github.dwickern" % "sbt-swagger-play" % "0.5.0")
//addCompilerPlugin("com.github.takezoe" %% "runtime-scaladoc-reader" % "1.0.3")
